PREFIX calli:<http://callimachusproject.org/rdf/2009/framework#>

ASK {
	{
		?group calli:member $credential
		{
			$this calli:administrator ?group
		} UNION {
			$this calli:editor ?group
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST" || $method = "PUT" || $method = "DELETE")
			FILTER (!bound($query) || $query = "edit")
		} UNION {
			{
				$this calli:reader ?group
			} UNION {
				$this calli:subscriber ?group
			} UNION {
				$this calli:contributor ?group
			} UNION {
				$this calli:editor ?group
			}
			FILTER ($method = "GET" || $method = "HEAD")
			FILTER (!bound($query) || $query = "view")
		} UNION {
			{
				$this calli:subscriber ?group
			} UNION {
				$this calli:contributor ?group
			} UNION {
				$this calli:editor ?group
			}
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST" && $query = "discussion")
			FILTER ($query = "discussion" || $query = "history" || $query = "whatlinkshere" || $query = "relatedchanges")
		} UNION {
			{
				$this calli:contributor ?group
			} UNION {
				$this calli:editor ?group
			}
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST")
			FILTER (regex($query, "^create="))
		} UNION {
			$this calli:author ?group
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST")
			FILTER ($query = "create")
		}
	} UNION {
		{
			$this calli:administrator $credential
		} UNION {
			$this calli:editor $credential
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST" || $method = "PUT" || $method = "DELETE")
			FILTER (!bound($query) || $query = "edit")
		} UNION {
			{
				$this calli:reader $credential
			} UNION {
				$this calli:subscriber $credential
			} UNION {
				$this calli:contributor $credential
			} UNION {
				$this calli:editor $credential
			}
			FILTER ($method = "GET" || $method = "HEAD")
			FILTER (!bound($query) || $query = "view")
		} UNION {
			{
				$this calli:subscriber $credential
			} UNION {
				$this calli:contributor $credential
			} UNION {
				$this calli:editor $credential
			}
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST" && $query = "discussion")
			FILTER ($query = "discussion" || $query = "history" || $query = "whatlinkshere" || $query = "relatedchanges")
		} UNION {
			{
				$this calli:contributor $credential
			} UNION {
				$this calli:editor $credential
			}
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST")
			FILTER (regex($query, "^create="))
		} UNION {
			$this calli:author $credential
			FILTER ($method = "GET" || $method = "HEAD" || $method = "POST")
			FILTER ($query = "create")
		}
	}
}
