PREFIX calli:<http://callimachusproject.org/rdf/2009/framework#>
SELECT ?realm {
    {
        ?realm calli:hasComponent* <$target>
        FILTER EXISTS {?realm a calli:Realm}
    } UNION {
        BIND (</> AS ?realm)
        BIND (true AS ?default)
    }
}
ORDER BY ?default desc(?realm) LIMIT 1
