PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX calli:<http://callimachusproject.org/rdf/2009/framework#>
SELECT DISTINCT ?heading ?label ?link ?group
WHERE {
    {
        <$this> calli:item ?item
    } UNION {
        <$this> calli:item [rdfs:label ?heading; calli:item ?item]
    }
    ?item rdfs:label ?label.
    OPTIONAL {
        ?item calli:position ?position
    }
    OPTIONAL {
        ?item calli:link ?link
    }
    OPTIONAL {
        ?item calli:group ?group
    }
}
ORDER BY ?position ?label
LIMIT 100