# page-info.rq
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:<http://www.w3.org/2008/05/skos-xl#>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX prov:<http://www.w3.org/ns/prov#>
PREFIX calli:<http://callimachusproject.org/rdf/2009/framework#>
SELECT DISTINCT ?updated ?iri ?label {
    {
        <$target> prov:wasGeneratedBy [prov:endedAtTime ?updated]
    } UNION {
        ?iri calli:hasComponent* <$target>
        OPTIONAL {
            ?iri skos:prefLabel ?label
        } OPTIONAL {
            ?iri foaf:name ?label
        } OPTIONAL {
            ?iri rdfs:label ?label
        } OPTIONAL {
            ?iri skosxl:literalForm ?label
        } OPTIONAL {
            ?iri dcterms:title ?label
        }
    }
} ORDER BY ?iri