#
# @Cache-Control: no-store
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX keyword:<http://www.openrdf.org/rdf/2011/keyword#>

SELECT REDUCED ?resource ?label ?comment {
    {
        SELECT REDUCED ?resource {
            {
                ?resource a owl:Class; keyword:phone ?soundex
                FILTER sameTerm(?soundex, keyword:soundex("$q"))
                FILTER (strlen("$q") > 2)
            } UNION {
                ?resource a owl:Class; rdfs:label "$q"
                FILTER (strlen("$q") < 3)
            } UNION {
                ?resource a owl:Class
                FILTER sameTerm(?resource, iri(<$iri>))
            }
        } LIMIT 100
    }
    FILTER (isIRI(?resource))
    ?resource rdfs:label ?label
    FILTER isLiteral(?label)
    FILTER (strlen("$q") < 3 || regex(?label, keyword:regex("$q")))
    OPTIONAL {
        ?resource rdfs:comment ?comment
    }
} ORDER BY ?label LIMIT 100
