#
# @Cache-Control: no-store
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX keyword:<http://www.openrdf.org/rdf/2011/keyword#>

SELECT ?resource ?label {
    {
        SELECT * {
            ?resource a skos:Concept; keyword:phone ?soundex
            FILTER sameTerm(?soundex, keyword:soundex("$q"))
            FILTER (strlen("$q") > 0)
        } LIMIT 100
    }
    FILTER (isIRI(?resource))
    ?resource skos:prefLabel ?label
    FILTER isLiteral(?label)
    FILTER regex(?label, keyword:regex("$q"))
} ORDER BY ?label LIMIT 100
