PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX prov:<http://www.w3.org/ns/prov#>
SELECT REDUCED ?label ?note ?revision ?modified ?user (coalesce(?name, replace(str(?user),"^.*/","")) AS ?name)
WHERE {
    {
        <$target> skos:prefLabel ?label
    } UNION {
        <$target> rdfs:label ?label
    } UNION {
        GRAPH ?revision { <$target> skos:editorialNote ?note }
        ?revision prov:wasGeneratedBy ?activity .
        ?activity prov:endedAtTime ?modified .
        OPTIONAL { ?activity prov:wasAssociatedWith ?user
            OPTIONAL { ?user rdfs:label ?name }
        }
    }
}
ORDER BY ?modified
LIMIT 100