#
# Copyright (c) 2014 3 Round Stones Inc., Some Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# @Cache-Control: no-store
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX schema: <http://schema.org/>
PREFIX msg: <http://www.openrdf.org/rdf/2011/messaging#>
PREFIX calli: <http://callimachusproject.org/rdf/2009/framework#>
PREFIX : <#>

SELECT ?cls (COALESCE(?label, replace(str(?cls), "^.*[/#:]", "")) AS ?name) ?comment {
    GRAPH <$graph> { ?cls a owl:Class }
    OPTIONAL { ?cls rdfs:label ?label }
    OPTIONAL { ?cls rdfs:comment ?comment }
    FILTER isIRI(?cls)
}
LIMIT 1000
