#
# @Cache-Control: no-store
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX schema: <http://schema.org/>
PREFIX msg: <http://www.openrdf.org/rdf/2011/messaging#>
PREFIX calli: <http://callimachusproject.org/rdf/2009/framework#>
PREFIX : <#>

SELECT ?cls (COALESCE(?label, replace(str(?cls), "^.*[/#:]", "")) AS ?name) ?comment {
    GRAPH <$graph> { ?cls a owl:Class }
    OPTIONAL { ?cls rdfs:label ?label }
    OPTIONAL { ?cls rdfs:comment ?comment }
    FILTER isIRI(?cls)
}
LIMIT 1000