#
# @Cache-Control: max-age=60
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX calli: <http://callimachusproject.org/rdf/2009/framework#>

SELECT (concat('?create=', encode_for_uri(str(?cls))) AS ?url)
    ?label ?comment ?icon (substr(min(?order),2) AS ?author)
WHERE {
    ?cls rdf:type/rdfs:subClassOf? <../types/Creatable>;
        rdfs:label ?label;
        rdfs:comment ?comment;
        calli:icon ?icon;
        calli:create ?create
    FILTER (?create != <../templates/file-create.xhtml>)
    FILTER EXISTS {
        ?cls calli:author ?domain
        {
            FILTER (?domain = <$user>)
        } UNION {
            ?domain calli:member <$user>
        } UNION {
            ?domain calli:everyoneFrom []
        } UNION {
            ?domain calli:anonymousFrom []
        }
    }
    ?cls calli:author ?group .
    ?group rdfs:label ?author .
    BIND (
        concat(
            if (?group = </auth/groups/everyone>, "1",
            if (?group = </auth/groups/users>, "2",
            if (?group = </auth/groups/staff>, "3",
            if (?group = </auth/groups/power>, "4",
            if (?group = </auth/groups/admin>, "5",
            "6"
            ))))),
            ?author
        ) AS ?order
    )
} GROUP BY ?cls ?label ?comment ?icon ORDER BY asc(min(?order)) ?author ?label
