#
# @Cache-Control: max-age=43200
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX calli: <http://callimachusproject.org/rdf/2009/framework#>

SELECT
    (<../styles> AS ?styles)
    (<../scripts> AS ?scripts)
    (if(bound(?layout),?layout,<../theme/layout.xhtml>) AS ?layout)
    (if(bound(?favicon),?favicon,<../images/callimachus-icon.ico>) AS ?favicon)
    (if (bound(?menu),concat(str(?menu),'?items'),?menu) AS ?menu)
    ?variation
    ?rights
WHERE {
    {
        <$realm> a calli:Realm
    } OPTIONAL {
        <$realm> calli:theme [calli:layout ?layout]
    } OPTIONAL {
        <$realm> calli:favicon ?favicon
    } OPTIONAL {
        <$realm> calli:menu ?menu
    } OPTIONAL {
        <$realm> calli:variation ?variation
    } OPTIONAL {
        <$realm> calli:rights ?rights
    }
}
